=== sanbee/capps/CASACode/code/xmlcasa/xml/casa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xsd:element name="casaxml">
    <xsd:complexType mixed="true">
      <xsd:sequence>
        <xsd:element ref="tool"/>
        <xsd:element ref="task"/>
        <xsd:element ref="casaparams"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="tool">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="needs"/>
        <xsd:element ref="shortdescription"/>
        <xsd:element ref="keyword"/>
        <xsd:element ref="code"/>
        <xsd:element ref="description"/>
        <xsd:element ref="method"/>
        <xsd:element ref="comments"/>
      </xsd:choice>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="module" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="needs" type="xsd:string"/>

  <xsd:element name="shortdescription" type="xsd:string"/>

  <xsd:element name="keyword" type="xsd:string"/>

  <xsd:element name="code">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="include"/>
        <xsd:element ref="private"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="include" type="xsd:string"/>

  <xsd:element name="private" type="xsd:string"/>

  <xsd:element name="description">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="link"/>
        <xsd:element ref="example"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="link">
    <xsd:complexType>
     <xsd:simpleContent>
       <xsd:extension base="xsd:string">
      <xsd:attribute name="anchor" type="xsd:string" use="required"/>
       </xsd:extension>
     </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="example">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="link"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="task">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="shortdescription"/>
        <xsd:element ref="input"/>
        <xsd:element ref="inout"/>
        <xsd:element ref="returns"/>
        <xsd:element ref="description"/>
        <xsd:element ref="example"/>
        <xsd:element ref="output"/>
        <xsd:element ref="link"/>
        <xsd:element ref="comments"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="method">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="shortdescription"/>
        <xsd:element ref="input"/>
        <xsd:element ref="inout"/>
        <xsd:element ref="returns"/>
        <xsd:element ref="description"/>
        <xsd:element ref="example"/>
        <xsd:element ref="output"/>
        <xsd:element ref="link"/>
        <xsd:element ref="comments"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="input">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="param"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="param">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="description"/>
        <xsd:element ref="value"/>
        <xsd:element ref="any"/>
        <xsd:element ref="allowed"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="units" type="xsd:string"/>
      <xsd:attribute name="kind" type="xsd:string"/>
      <xsd:attribute name="mustexist" type="xsd:string"/>
      <xsd:attribute name="subparam" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="returns">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="any"/>
        <xsd:element ref="shortdescription"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="value">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="value"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string"/>
      <xsd:attribute name="limittypes" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="any">
    <xsd:complexType>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="choice" type="xsd:string"/>

  <xsd:element name="inout">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="param"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="output">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="param"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="defaultrecord">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="value"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="comments">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="link"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="range">
    <xsd:complexType>
      <xsd:attribute name="min" type="xsd:string" use="required"/>
      <xsd:attribute name="max" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== sanbee/capps/trunk/CASACode/code/xmlcasa/tasks/concat.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<task type="function" name="concat" category="utility">
<shortdescription>Concatenate several visibility data sets.</shortdescription>

<input>
  <param type="stringArray" name="vis" mustexist="true">
    <description>Name of input visibility files to be concatenated</description>
    <value></value>
  </param>

  <param type="string" name="concatvis">
    <description>Name of output visibility file</description>
    <value></value>
  </param>
  
  <param type="any" name="freqtol" >
    <description>Frequency shift tolerance for considering data as the same spwid</description>
    <any type="variant"/>
    <value type="string"></value>
  </param>

  <param type="any" name="dirtol">
    <description>Direction shift tolerance for considering data as the same field</description>
    <any type="variant"/>
    <value type="string"></value>
  </param>

  <param type="bool" name="timesort" >
    <description>If true, sort by TIME in ascending order</description>
    <value>False</value>
  </param>
</input>
<example>

The list of data sets given in the vis argument are concatenated into an output
data set in concatvis.  If concatvis already exists (e.g., it is the same as the
first input data set), then the other input data sets will be appended to the
concatvis data set.  There is no limit to the number of input data sets.

If none of the input data sets have any scratch columns (model and corrected
columns), none are created in the concatvis.  Otherwise these columns are
created on output and initialized to their default value (1 in model column,
data in corrected column) for those data with no input columns.

Spectral windows for each data set with the same chanelization, and within a
specified frequency tolerance of another data set will be combined into one
spectral window.

A field position in one data set that is within a specified direction tolerance
of another field position in any other data set will be combined into one
field.  The field names need not be the same---only their position is used.


Keyword arguments:
vis -- Name of input visibility files to be combined
	default: none; example: vis = 'mydata.ms',
             vis=['src2.ms','ngc5921.ms','ngc315.ms']
concatvis -- Name of visibility file that will contain the concatenated data
	note: if this file exits on disk then the input files are 
              added to this file.  Otherwise the new file contains  
	      the concatenated data.  Be careful here when concatenating to
              an existing file.
	default: none; example: concatvis='src2.ms'
	         example: concatvis='outvis.ms'

        other examples: 
           concat(vis=['src2.ms','ngc5921.ms'], concatvis='src2.ms')
               will concatenate 'ngc5921.ms' into 'src2.ms', and the original
	       src2.ms is lost

	   concat(vis=['src2.ms','ngc5921.ms'], concatvis='out.ms') 
               will concatenate 'ngc5921.ms' and 'src2.ms' into a file named 
               'out.ms'; the original 'ngc5921.ms' and 'src2.ms' are untouched.

           concat(vis=['v1.ms','v2.ms'], concatvis = 'vall.ms')
              then
           concat(vis=['v3.ms','v4.ms'], concatvis = 'vall.ms')
             vall.ms will contains v1.ms+v2.ms+v3.ms+v4.ms

     Note: run flagmanager to save flags in the concatvis

freqtol -- Frequency shift tolerance for considering data to be in the same
           spwid.  The number of channels must also be the same.
	default: ''  do not combine unless frequencies are equal
	example: freqtol='10MHz' will not combine spwid unless they are
	   within 10 MHz.
        Note: This option is useful to conbine spectral windows with very slight
           frequency differences caused by Doppler tracking, for example.

dirtol -- Direction shift tolerance for considering data as the same field
	default: '' means always combine.
	example: dirtol='1.arcsec' will not combine data for a field unless
	   their phase center differ by less than 1 arcsec.  If the field names
           are different in the input data sets, the name in the output data
           set will be the first relevant data set in the list.

timesort -- If true, the output visibility table will be sorted in time.
        default: false.  Data in order as read in.
	example: timesort=true
     Note: There is no constraint on data that is simultaneously observed for
        more than one field; for example multi-source correlation of VLBA data.

</example> 

</task>
</casaxml>

=== sanbee/capps/trunk/CASACode/code/xmlcasa/tasks/sdimprocess.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/xmlcasa/xml/casa.xsd">


<!-- This is the param set for sdimprocess -->

<task type="function" name="sdimprocess" startup="false" category="single dish">

  <shortdescription>SD task: task for single-dish image processing</shortdescription>

  <description>SD task for image processing including "Pressed-out" method and "Basket-Weaving"

        Task Version 2009-10-01 TN
</description>

  <input>
    <param type="any" name="sdimages"  mustexist="true">
            <description>name of input SD image (FITS or CASA image)</description>
            <any type="variant" limittype="string stringArray"/>
            <value type="stringArray">''</value>
    </param>

    <param type="string" name="mode">
            <description>processing mode ("press" or "basket")</description>
            <allowed kind="enum">
                <value>basket</value>
                <value>press</value>
            </allowed>
    </param>

    <param type="int" name="numpoly" subparam="true">
            <description>order of polynomial fit</description>
            <value>2</value>
    </param>

    <param type="double" name="beamsize" subparam="true">
            <description>beam size</description>
            <any type="variant" limittype="double string"/>
            <value type="double">0.0</value>
    </param>
    
    <param type="any" name="smoothsize" subparam="true">
            <description>size of smoothing beam</description>
            <any type="variant" limittype="double string"/>
            <value type="double">2.0</value> 
    </param>

    <param type="any" name="direction" subparam="true">
            <description>scan direction in unit of degree</description>
            <any type="variant" limittype="double doubleArray"/>
            <value type="doubleArray"></value>
    </param>

    <param type="any" name="masklist" subparam="true">
            <description>mask width (on percentage)</description>
            <any type="variant" limittype="double doubleArray"/>
            <value type="double">1.0</value>
    </param>

    <param type="double" name="tmax">
            <description>maximum value used for process</description>
            <value>0.0</value>
    </param>

    <param type="double" name="tmin">
            <description>minimum value used for process</description>
            <value>0.0</value>
    </param>

    <param type="string" name="imagename">
	    <description>output CASA image name</description>
	    <value></value>
    </param>

    <param type="bool" name="overwrite">
            <description>overwrite option for imagename</description>
            <value>False</value>
    </param>

    <constraints>
            <when param="mode">
                <equals value="basket">
                    <default param="direction"><value type="doubleArray"></value></default>
                    <default param="masklist"><value type="double">1.0</value></default>
                </equals>
                <equals value="press">
                    <default param="numpoly"><value type="int">2</value></default>
                    <default param="beamsize"><value type="double">0.0</value></default>
                    <default param="smoothsize"><value type="double">2.0</value></default>
                    <default param="direction"><value type="double">0.0</value></default>
                </equals>
            </when>
   </constraints>

  </input>

  <returns type="void"/>

  <example>
  Keyword arguments:
        sdimages -- name of input SD (FITS or CASA) image
        mode -- processing mode
                default: 'basket'
                options: 'basket', 'press'
               direction -- scan direction in unit of degree
                   default: []
                   example: [0.0,90.0]
               masklist -- mask width for Basket-Weaving on percentage
                   default: 1.0 (1.0% of map size)
               numpoly -- order of polynomial fit in Presssed-out
                   default: 2
               beamsize -- beam size 
                   default: 0.0
                   example: 10.0 (interpreted as '10arcsec'), '1arcmin'
               smoothsize -- smoothing beam in Pressed-out
                   default: 2.0 (interpreted as 2.0 * beamsize)
                   example: '1arcmin' (set smoothsize directly)
        tmax -- maximum value used for process
                default: 0.0 (no threshold in maximum)
                example: 10.0 (mask data larger value than 10.0)
        tmin -- minimum value used for process
                default: 0.0 (no threshold in minimum)
                example: -10.0 (mask data smaller value than -10.0)
        imagename -- output CASA image name
                default: '' (use default name)
                example: 'output.im'
        overwrite -- overwrite option for imagename
                default: False (not overwrite)
                options: True, False
                example: if True, existing file will be overwritten


        DESCRIPTION:

        Task sdimprocess is used to remove a scanning noise that appears 
        as a striped noise pattern along the scan direction in a raster 
        scan data. 

        By default, the scanning noise is removed by using the 
        'Basket-Weaving' method (Emerson &amp; Grave 1988) that requires 
        multiple images that observed exactly the same area with different 
        scanning direction. If only one image is available, the 'Pressed-out' 
        method (Sofue &amp; Reich 1979) can be used to remove the scanning 
        effect.

        For 'Basket-Weaving', scanning directions must have at least two 
        different values. Normally, the scanning direction should be 
        specified for each input image. Otherwise, specified scanning 
        directions will be used iteratively. The masklist is a width of 
        masking region in the Fourier plane. It is specified as a fraction 
        (percentage) of the image size. 

        For 'Pressed-out', the scanning direction must be unique. There are 
        two ways to specify a size of smoothing beam used for process. One 
        is to specify smoothing size directly. To do this, smoothsize should 
        be specified as string that consists of a numerical value and an unit 
        (e.g. '10.0arcsec'). A value of beamsize will be ignored in this case. 
        Another way to specify smoothing size is to set an observed beam size 
        and indicate smoothing size as a scale factor of the observed beam 
        size. In this case, the beamsize is interpreted as the observed beam 
        size, and the smoothsize is the scale factor. If the beamsize is 
        provided as float value, its unit is assumed to 'arcsec'. It is also 
        possible to set the beamsize as string consisting of the numerical 
        value and the unit. The smoothsize must be float value.

        The sdimages only allows an image data (CASA or FITS), and not does
        not work with MS or Scantable. The direction is an angle with respect 
        to the horizontal direction, and its unit is degree. Any value may be 
        interpreted properly, but the value ranging from 0.0 to 180.0 will be 
        secure. The tmax and the tmin is used to specify a threshold that 
        defines a range of spectral values used for processing. The data point 
        that has the value larger than tmax or smaller than tmin will be 
        excluded from the processing. The default (0.0) is no threshold. 
        The imagename specifies an output CASA image name. If the imagename 
        is empty, the default name ('sdimprocess.out.im') will be used. 
  </example>

</task>

</casaxml>

=== sanbee/capps/trunk/CASACode/code/xmlcasa/tasks/sdscale.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd file:///opt/casa/code/xmlcasa/xml/casa.xsd">
<!-- This is the param set for sdscale -->

<task type="function" name="sdscale" startup="false" category="single dish">

  <shortdescription>ASAP SD task: scale the sd spectra</shortdescription>

  <description>
        ASAP SD task (based on the ALMATST5 recommendations):
        Scale the sd spectra

        Task Version 2008-01-29 TT
</description>

  <input>

    <param type="string" name="sdfile"  mustexist="true">
    <description>name of input SD dataset</description>
    <value></value>
    </param>

    <param type="any" name="antenna">
            <description>antenna name or id (only effective for MS input)</description>
            <any type="variant" limittype="string int"/>
            <value type="int">0</value>
    </param> 

    <param type="any" name="factor">
	    <description>scaling factor (float or float list)</description>
            <any type="variant" limittype="string double doubleArray"/>
	    <value type="double">1.0</value>
    </param>

    <param type="bool" name="scaletsys">
            <description>scaling of associated Tsys</description>
            <value>True</value>
    </param>

    <param type="string" name="outfile">
            <description>if specified write the scaled data to a separate scantable file</description>
            <value></value>
    </param>

    <param type="bool" name="overwrite">
            <description>overwrite the output file if already exists</description>
            <value>False</value>
    </param>

    </input>

  <returns type="void"/>

  <example>
        Keyword arguments:
        sdfile -- name of input SD dataset
        antenna -- antenna name or id (only effective for MS input). 
        factor -- scaling factor. float or one- or two-dimensional float list.
                  default: 1 (no scaling)
        scaletsys -- scaling of associated Tsys
                    default: True
        outfile -- output file name 
                   outfile='' will write the data to a file named,
                   &lt;sdfile&gt;_scaled&lt;factor&gt;
                   default: ''
        overwrite -- overwrite the output file if already exists
                options: (bool) True,False
                default: False


        DESCRIPTION:

        Task sdscale performs scaling of single-dish spectra.
        By setting scaletsys = True, associated Tsys is also scaled.
        Tsys informations are written in the casalogger and they are 
        automatically stored in 'casapy.log'. 
        The sdfile can be any of ASAP, MS, SDFITS, or RPFITS format.
        If outfile name is given or outfile=''(default), the scaled data 
        is written to a new file with the same format as the input data 
        (Note: in case of the RPFITS format input data, it will be written 
        to SDFITS format).

        The scaling factor, factor, accepts both scalar type and list 
        type value. The list must be one or two dimensional. If factor is 
        one dimensional, its length must coincide with a number of spectral 
        channel. If factor is two dimensional, its shape must be 
        (n, 1) or (n, m), where n is a number of spectrum, while m is a 
        number of channel for each spcetum. m can be variable for each 
        spectrum. In addition, the factor can be an ASCII filename that 
        stores a space-separated list of scaling factor consisting of 
        adequate number of rows and columns. For example, if the contents 
        of input ASCII file is shown as, 

           0.5 0.3 0.2
           1.0 0.2 0.9

        it is interpreted as a list [[0.5, 0.3, 0.2],[1.0, 0.2, 0.9]]. 

        WARNING for the GBT raw SDFITS format data as input:
        Currently, all SDtasks cannot handle GBT raw SDFITS format data
        (in which the data are stored in multiple tables within SDFITS).
        It may be still possible to reduce GBT data after some
        preprocessing (outside CASA) of the raw SDFITS to a SDFITS with
        a single data table or to other data formats handled by SDtasks.


  </example>

</task>

</casaxml>
