=== sanbee/capps/CASACode/code/xmlcasa/xml/casa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xsd:element name="casaxml">
    <xsd:complexType mixed="true">
      <xsd:sequence>
        <xsd:element ref="tool"/>
        <xsd:element ref="task"/>
        <xsd:element ref="casaparams"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="tool">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="needs"/>
        <xsd:element ref="shortdescription"/>
        <xsd:element ref="keyword"/>
        <xsd:element ref="code"/>
        <xsd:element ref="description"/>
        <xsd:element ref="method"/>
        <xsd:element ref="comments"/>
      </xsd:choice>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="module" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="needs" type="xsd:string"/>

  <xsd:element name="shortdescription" type="xsd:string"/>

  <xsd:element name="keyword" type="xsd:string"/>

  <xsd:element name="code">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="include"/>
        <xsd:element ref="private"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="include" type="xsd:string"/>

  <xsd:element name="private" type="xsd:string"/>

  <xsd:element name="description">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="link"/>
        <xsd:element ref="example"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="link">
    <xsd:complexType>
     <xsd:simpleContent>
       <xsd:extension base="xsd:string">
      <xsd:attribute name="anchor" type="xsd:string" use="required"/>
       </xsd:extension>
     </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="example">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="link"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="task">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="shortdescription"/>
        <xsd:element ref="input"/>
        <xsd:element ref="inout"/>
        <xsd:element ref="returns"/>
        <xsd:element ref="description"/>
        <xsd:element ref="example"/>
        <xsd:element ref="output"/>
        <xsd:element ref="link"/>
        <xsd:element ref="comments"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="method">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="shortdescription"/>
        <xsd:element ref="input"/>
        <xsd:element ref="inout"/>
        <xsd:element ref="returns"/>
        <xsd:element ref="description"/>
        <xsd:element ref="example"/>
        <xsd:element ref="output"/>
        <xsd:element ref="link"/>
        <xsd:element ref="comments"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="input">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="param"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="param">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="description"/>
        <xsd:element ref="value"/>
        <xsd:element ref="any"/>
        <xsd:element ref="allowed"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="units" type="xsd:string"/>
      <xsd:attribute name="kind" type="xsd:string"/>
      <xsd:attribute name="mustexist" type="xsd:string"/>
      <xsd:attribute name="subparam" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="returns">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="any"/>
        <xsd:element ref="shortdescription"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="value">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="value"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string"/>
      <xsd:attribute name="limittypes" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="any">
    <xsd:complexType>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="choice" type="xsd:string"/>

  <xsd:element name="inout">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="param"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="output">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="param"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="defaultrecord">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="value"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="comments">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="link"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="range">
    <xsd:complexType>
      <xsd:attribute name="min" type="xsd:string" use="required"/>
      <xsd:attribute name="max" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== sanbee/capps/CASACode/code/xmlcasa/tasks/exportasdm.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/xmlcasa/xml/casa.xsd">


<task type="function" name="exportasdm" category="import/export" visibility="experimental">

  <shortdescription>Convert a CASA visibility file (MS) into an ALMA Science Data Model</shortdescription>

  <input>

    <param type="string" name="vis" kind="ms" mustexist="true">
          <description>MS name</description>
          <value></value>
    </param>


    <param type="string" name="asdm" kind="asdm" mustexist="false">
          <description>Name of output ASDM directory (on disk)</description>
          <value></value>
    </param>

    <param type="string" name="datacolumn"  ignorecase="True">
	    <description>specifies which MS data column is used to fill the visibilites in the ASDM</description>
	    <value>DATA</value>
	    <allowed kind="enum">
	       <value>data</value>
	       <value>corrected</value>
	       <value>model</value>
	    </allowed>
    </param>
    <param type="string" name="archiveid">
	    <description>the X0 in uid://X0/X1/X&lt;running&gt;</description>
	    <value>S0</value>
    </param>
    <param type="string" name="rangeid">
	    <description>the X1 in uid://X0/X1/X&lt;running&gt;</description>
	    <value>X1</value>
    </param>
    <param type="string" name="subscanduration">
	    <description>maximum duration of a subscan in the output ASDM</description>
	    <value>24h</value>
    </param>
    <param type="string" name="sbduration">
	    <description>maximum duration of a scheduling block (and therefore exec block) in the output ASDM</description>
	    <value>2700s</value>
    </param>
    <param type="bool" name="apcorrected">
	    <description>data to be marked as having atmospheric phase correction</description>
	    <value>True</value>
    </param>
    <param type="bool" name="verbose">
	    <description>produce log output</description>
	    <value>True</value>
    </param>
    <param type="bool" name="showversion">
	    <description>Report the version of ASDM class set being used</description>
	    <value>True</value>
    </param>

    </input>

  <returns type="bool"/>

  <example>

  Keyword arguments:
  vis -- MS name,
         default: none

  asdm -- Name of output ASDM file (directory),
          default: none; example: asdm='ExecBlock3'

  datacolumn -- specifies which of the MS data columns (DATA,
           CORRECTED_DATA, or MODEL_DATA) should be used as the
           visibilities in the ASDM, default: DATA

  archiveid -- the X0 in uid://X0/X1/X&lt;running&gt;
               default: "S0"

  rangeid -- the X1 in uid://X0/X1/X&lt;running&gt;
             default: "X1"

  subscanduration -- maximum duration of a subscan in the output ASDM
	             default: "24h"

  sbduration -- maximum duration of a scheduling block in the output ASDM
	             default: "2700s"

  apcorrected -- If true, the data in column datacolumn will be marked
	         as having atmospheric phase correction, default: True

  verbose     -- produce log output, default: True

  showversion -- report the version of the ASDM class set, 
                 default: True


  exportasdm(vis='ngc4826.ms', asdm='uid___S021_X1418_X1', 
  datacolumn='corrected', archiveid='S021', rangeid='X1418', 
  verbose=False)
  will produce an ASDM named 'uid___S021_X1418_X1' using the 
  datacolumn 'CORRECTED_DATA' in the MS 'ngc4826.ms' with minimal
  log output. 

  </example>

</task>

</casaxml>

=== sanbee/capps/trunk/CASACode/code/xmlcasa/tasks/fixvis.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>

<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<!-- Documentation here.                                                -->

<task type="function" name="fixvis" category="data editing, utility" visibility="experimental">

<shortdescription>Recalculates or converts (u, v, w)<!--  and Changes Phase Center. --></shortdescription>
<description>
     This corrects visibilities, and/or their (u, v, w) positions, for various
     effects that can be calculated without fitting a model to the data.

     The effects include:
     \begin{itemize}
       \item calculating (u, v, w) coordinates,
<!--        \item changing the phase tracking center(s),
       \item correcting for differential aberration,  -->
       \item changing the refcode (i.e. B1950 to J2000, etc.),
<!--        \item changing the projection, as in (-)NCP to SIN,  -->
       \item refocusing (Not yet incorporated).
     \end{itemize}
</description>

<input>
    <param type="string" name="vis" kind="ms" mustexist="true">
        <description>Name of the input visibility set.</description>
        <value></value>
        <example>vis='ngc5921.ms'</example>
    </param>
    <param type="string" name="outputvis" kind="ms">
        <description>Name of the output visibility set.  (Can be the same as vis.)</description>
        <value></value>
        <example>vis='ngc5921\_fixedvis.ms'</example>
    </param>
    <param type="any" direction="in" name="fields">
      <description>Fields to operate on.  Blank = all.</description>
      <any type="variant"/>
      <value>""</value>
    </param>
    <param type="string" name="refcode">
      <!-- Don't wrap! -->
        <description>Reference frame to use for outputvis.  WARNING: clean and the im tool ignore the reference frame claimed by the UVW column (it is often mislabelled as ITRF when it is really J2000) and instead assume the (u, v, w)s are in the same frame as the phase tracking center.  fixvis does not yet force the UVW column and field centers to use the same reference frame!  Blank = use the phase tracking frame of vis.</description>
        <value></value>
        <example>refcode = 'B1950_VLA'</example>
    </param>
    <param type="bool" name="reuse">
      <description>Start from the UVWs in vis (True) or calculate them from the antenna positions?</description>
      <value>True</value>
    </param>
<!--     <param type="string" name="proj">
        <description>Projection code to use for the output.</description>
        <value></value>
        <example>proj = 'SIN'</example>
    </param>  -->
<!--     <param type="any" direction="in" name="phasecenters">
        <description>Phase tracking centers to use for the output, in the same order as fields.  Use LON LAT offsets (i.e. "-0.5s 0.5s") in the same frame as refcode or absolute directions (i.e. "J2000 19h55m05.6s -34d44m43.0s"). Blank = use old ones.</description>
	<any type="variant"/>
        <value>""</value>
        <example></example>
    </param>  -->
</input>

<!-- DIRTY HACK: <description> does not currently (2009-03-10) make it into help or ?,
                 but <example> does. -->
<!-- <description> -->
<example>

This task calculates (u, v, w) coordinates, and optionally changes the
reference frame (i.e. B1950_VLA to J2000 and back).

Not yet implemented, or incorporated in this task, are:
   changing the phase tracking center(s),
   changing the projection (i.e SIN to or from (-)NCP).
   correcting for differential aberration,
   adjusting antenna positions,
   fixing clock errors,
   and refocusing to a finite distance.

Input Parameters:

vis       --- Name of input measurement set.
              ex: vis='my.ms'

outputvis --- Name of the output measurement set.  (Can be the same as vis.)
              ex: outputvis = 'myrefocused.ms'

fields    --- Selection string for the fields to operate on.  '' = all.

refcode   --- Reference frame to use for the generated (u, v, w)s,
              i.e. 'J2000', 'B1950', 'GALACTIC', etc..  A full list of
              codes can be gotten from
              'csys=cs.newcoordsys(True);csys.referencecode('dir',True);csys.done()'

              The reference frame cannot be changed when only some of the
              fields are selected.

              Default: '' (use the reference frame of the phase tracking
                           center(s) in the input ms)

              ex: refcode = 'B1950_VLA'

              WARNING: clean and the im tool ignore the reference frame
              claimed by the UVW column (it is often mislabelled as ITRF
              when it is really J2000) and instead assume the (u, v, w)s
              are in the same frame as the phase tracking center(s) of the
              MS.  fixvis does not yet force the UVWs and fields to use the
              same frame!

reuse     --- If True, start from the UVWs in vis, e.g. rotate them for an
              equinox conversion.  Otherwise, freshly calculate them from
              the antenna positions.

              Set to True if you think fixvis will produce more accurate UVWs
              than the ones in vis.  (Depends on when and where the observation
              was made and/or filled.)

              Default: True

<!-- proj       Projection code to use for the output.  A list of codes can be
              gotten from 'csys = cs.newcoordsys(True);csys.projection('all');csys.done()'
              Cannot be changed when only some of the fields are selected.
              Default '' = projection of input ms.
              ex: proj = 'TAN' -->

<!-- </description> -->

<!-- <example> -->
Example:

fixvis(vis='my.ms', outputvis='myrefocused.ms', refcode='J2000', reuse=False)

</example>

</task>

</casaxml>

=== sanbee/capps/CASACode/code/xmlcasa/tasks/importfitsidi.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
      file:///opt/casa/code/xmlcasa/xml/casa.xsd">

      <task type="function" name="importfitsidi" category="import/export">
	<shortdescription>Convert a FITS-IDI file to a CASA visibility data set</shortdescription>
	<description>Convert a FITS-IDI file to a CASA visiblity data set.
	</description>
	<input>
		<param type="stringArray" mustexist="true" name="fitsidifile">
			<description>Name(s) of input FITS-IDI file(s)</description>
			<value></value>
		</param>

		<param type="string" name="vis">
			<description>Name of output visibility file (MS)</description>
			<value></value>
		</param>
	</input>

<example>
	If several files are given, they will be concatenated into one MS.

        Keyword arguments:
        fitsidifile -- Name(s) of input FITS-IDI file(s)
                default: none; must be supplied 
		example='3C273XC1.IDI'
		example=['3C273XC1.IDI1','3C273XC1.IDI2'] 
        vis -- Name of output visibility file (MS)
                default: none; example: vis='3C273XC1.ms'
        async --  Run asynchronously
               default = false; do not run asychronously

 </example>
 </task>
 </casaxml>

=== sanbee/capps/trunk/CASACode/code/xmlcasa/tasks/uvcontsub2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<task type="function" name="uvcontsub2" category="modelling" visibility="experimental">
<shortdescription>Continuum fitting and subtraction in the uv plane CALIBRATION VERSION</shortdescription>
<description>
With this task, the continuum emission is estimated from the 
spectral windows and channels selected by fitspw.  Currently,
only a constant continuum (fitorder=0) is supported; this will
be generalized in the near future.   The data may be averaged 
in time to increase the signal to noise for each continuum
estimate.  This fit represents a model of the continuum in 
all channels.

The fitted continuum spectrum is subtracted from all channels 
selected in spw, and the result (presumably only line emission)
is stored in the CORRECTED_DATA of a <em>new</em> MS (vis + ".contsub").
The selected CORRECTED_DATA column of vis is copied to the DATA
column of the new ms.

If want_cont is True, the continuum fit is placed in the DATA
column of a second new MS (vis + ".cont").  N.B. because the
continuum model is necessarily a smoothed fit, images made with
it are liable to have their field of view reduced in some
strange way, and if possible should be compared with images
made by excluding the line channels.  A copy of the continuum
estimate is always placed in the MODEL_DATA column of vis + ".cont"
regardless of want_cont.

</description>
<input>
	<param type="string" name="vis" mustexist="true">
		<description>Name of input MS.  Output goes to vis + ".contsub"</description>
		<value></value>
	</param>

        <param type="any" name="field">
                <description>Select field(s) using id(s) or name(s)</description>
		<any type="variant" limittypes="string stringArray int intArray"/>
                <value type="string"></value>
        </param>

	<param type="string" name="fitspw">
		<description>Spectral window:channel selection for fitting the continuum</description>
		<value></value>
	</param>

        <param type="string" name="combine">
                <description>Data axes to combine for the continuum estimation (spw, scan, and/or field)</description>
                <value></value>
        </param>

	<param type="any" name="solint">
		<description>Continuum fit timescale</description>
                <any type="variant"/>
                <value type="string">int</value>
	</param>

	<param type="int" name="fitorder">
		<description>Polynomial order for the fit (CURRENTLY, only 0 is supported)</description>
		<value>0</value>
	</param>

	<param type="string" name="spw">
		<description>Spectral window selection for subtraction/export</description>
		<value></value>
	</param>

	<param type="bool" name="want_cont">
		<description>Create vis + ".cont" to hold the continuum estimate.</description>
		<value>False</value>
	</param>

</input>
<example>

	Continuum fitting and subtraction in the uv plane:
	
	With this task, the continuum emission is estimated from the 
        spectral windows and channels selected by fitspw.  Currently,
        only a constant continuum (fitorder=0) is supported; this will
        be generalized in the near future.   The data may be averaged 
        in time to increase the signal to noise for each continuum
        estimate.  This fit represents a model of the continuum in 
        all channels.
	
        The fitted continuum spectrum is subtracted from all channels 
        selected in spw, and the result (presumably only line emission)
        is stored in the CORRECTED_DATA of a <em>new</em> MS (vis + ".contsub").
        The selected CORRECTED_DATA column of vis is copied to the DATA
        column of the new ms.

        If want_cont is True, the continuum fit is placed in the DATA
        column of a second new MS (vis + '.cont').  N.B. because the
        continuum model is necessarily a smoothed fit, images made with
        it are liable to have their field of view reduced in some
        strange way, and if possible should be compared with images
        made by excluding the line channels.  A copy of the continuum
        estimate is always placed in the MODEL_DATA column of vis + '.cont'
        regardless of want_cont.


        The input MeasurementSet should have calibrated data in
        its CORRECTED_DATA column.

	Keyword arguments:
	vis -- Name of input visibility file
		default: none; example: vis='ngc5921.ms'
        field -- Field selection for continuum estimation and subtraction.
                default: field = '' means select all fields
                field = 1 # will get field_id=1 (if you give it an 
                        integer, it will retrieve the source with that index.
                field = '1328+307'  specifies source '1328+307'
		field = '13*' will retrieve '1328+307' and any other fields
		   beginning with '13'
	fitspw -- Selection of spectral windows and channels to use in the
	          fit for the continuum, using general spw syntax
		default: (all); example: fitspw='0:5~30;40~55'
        combine -- Data axes to combine for the continuum estimate
                default: '' --> solutions will break at scan, field, and spw
                      boundaries according to solint
              Options: '', 'spw'', 'scan', 'field', or any comma-separated
                       combination
              example: combine='spw' --> form spw-merged continuum estimate
	solint -- Timescale for per-baseline fit (units optional)
		default: 'int' --&gt; no averaging, fit every integration;
		example: solint='10s'  --&gt; average to 10s before fitting
                         10 or '10' --&gt; '10s' (unitless: assumes seconds)
                options: 'int' --&gt; per integration
                         'inf' --&gt; per scan
	fitorder -- Polynomial order for the fit of the continuum
		default: 0 (constant); example: fitorder=1
	spw -- Optional per spectral window selection of channels to include
               in the output.
	want_cont -- Create vis + '.cont' to hold the continuum estimate.
		default: 'False'; example: want_cont=True
		The continuum estimate will be placed in: vis.cont
        async -- Run task in a separate process (return CASA prompt)
                default: False; example: async=True

</example> 
</task>
</casaxml>
