=== sanbee/capps/CASACode/code/xmlcasa/xml/casa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xsd:element name="casaxml">
    <xsd:complexType mixed="true">
      <xsd:sequence>
        <xsd:element ref="tool"/>
        <xsd:element ref="task"/>
        <xsd:element ref="casaparams"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="tool">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="needs"/>
        <xsd:element ref="shortdescription"/>
        <xsd:element ref="keyword"/>
        <xsd:element ref="code"/>
        <xsd:element ref="description"/>
        <xsd:element ref="method"/>
        <xsd:element ref="comments"/>
      </xsd:choice>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="module" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="needs" type="xsd:string"/>

  <xsd:element name="shortdescription" type="xsd:string"/>

  <xsd:element name="keyword" type="xsd:string"/>

  <xsd:element name="code">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="include"/>
        <xsd:element ref="private"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="include" type="xsd:string"/>

  <xsd:element name="private" type="xsd:string"/>

  <xsd:element name="description">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="link"/>
        <xsd:element ref="example"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="link">
    <xsd:complexType>
     <xsd:simpleContent>
       <xsd:extension base="xsd:string">
      <xsd:attribute name="anchor" type="xsd:string" use="required"/>
       </xsd:extension>
     </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="example">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="link"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="task">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="shortdescription"/>
        <xsd:element ref="input"/>
        <xsd:element ref="inout"/>
        <xsd:element ref="returns"/>
        <xsd:element ref="description"/>
        <xsd:element ref="example"/>
        <xsd:element ref="output"/>
        <xsd:element ref="link"/>
        <xsd:element ref="comments"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="method">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="shortdescription"/>
        <xsd:element ref="input"/>
        <xsd:element ref="inout"/>
        <xsd:element ref="returns"/>
        <xsd:element ref="description"/>
        <xsd:element ref="example"/>
        <xsd:element ref="output"/>
        <xsd:element ref="link"/>
        <xsd:element ref="comments"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="input">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="param"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="param">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="description"/>
        <xsd:element ref="value"/>
        <xsd:element ref="any"/>
        <xsd:element ref="allowed"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="units" type="xsd:string"/>
      <xsd:attribute name="kind" type="xsd:string"/>
      <xsd:attribute name="mustexist" type="xsd:string"/>
      <xsd:attribute name="subparam" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="returns">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="any"/>
        <xsd:element ref="shortdescription"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="value">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="value"/>
      </xsd:choice>
      <xsd:attribute name="type" type="xsd:string"/>
      <xsd:attribute name="limittypes" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="any">
    <xsd:complexType>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="choice" type="xsd:string"/>

  <xsd:element name="inout">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="param"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="output">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="param"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="defaultrecord">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="value"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="comments">
    <xsd:complexType mixed="true">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="link"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="range">
    <xsd:complexType>
      <xsd:attribute name="min" type="xsd:string" use="required"/>
      <xsd:attribute name="max" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== sanbee/capps/trunk/CASACode/code/xmlcasa/tasks/importasdm.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/xmlcasa/xml/casa.xsd">


<task type="function" name="importasdm" category="import/export" visibility="experimental">

  <shortdescription>Convert an ALMA Science Data Model observation into a CASA visibility file</shortdescription>

  <input>

    <param type="string" name="asdm" kind="asdm" mustexist="true">
          <description>Name of input asdm directory (on disk)</description>
          <value></value>
    </param>

    <param type="string" name="vis" kind="ms">
          <description>Root name of the ms to be created. Note the .ms is NOT added </description>
          <value></value>
    </param>

    <param type="bool" name="singledish">
          <description>Set true to output single-dish data format </description>
          <value>False</value>
    </param>

    <param type="any" name="antenna" subparam="true">
            <description>antenna name or id</description>
            <any type="variant" limittype="string int"/>
            <value type="int">0</value>
    </param> 

    <param type="string" name="corr_mode" >
	    <description>specifies the correlation mode to be considered on input. A quoted string containing a sequence of ao, co, ac,or all separated by whitespaces is expected</description>
	    <value>all</value>
    </param>

    <param type="string" name="srt" >
	    <description>specifies the spectral resolution type to be considered on input. A quoted string containing a sequence of fr, ca, bw, or all separated by whitespaces is expected</description>
	    <value>all</value>
    </param>

    <param type="string" name="time_sampling" >
	    <description>specifies the time sampling (INTEGRATION and/or SUBINTEGRATION)  to be considered on input. A quoted string containing a sequence of i, si, or all separated by whitespaces is expected</description>
	    <value>all</value>
    </param>

    <param type="string" name="ocorr_mode" >
	    <description>output data for correlation mode AUTO_ONLY (ao) or CROSS_ONLY (co) or CROSS_AND_AUTO (ca)</description>
	    <value>ca</value>
	    <allowed kind="enum">
	       <value>co</value>
	       <value>ao</value>
	       <value>ca</value>
	    </allowed>
    </param>
    <param type="bool" name="compression">
	    <description>Flag for turning on data compression</description>
	    <value>False</value>
    </param>

    <param type="string" name="asis">
	    <description>Creates verbatim copies of the ASDMtables in the ouput measurement set.  Value given must be a string of table names separated by spaces; A * wildcard is allowed.</description>
	    <value></value>
    </param>

    <param type="string" name="wvr_corrected_data">
	    <description> Specifies which values are considerd in the SDM binary data to fill the DATA column in the MAIN table of the MS. Expected values for this option are: no, for uncorrected data (default), yes, for the corrected data, and both, for for corrected and uncorrected data. Note if both is selected two measurement sets are created, one with uncorrected data and the other with corrected data.  </description>
	    <value>no</value>
	    <allowed>
	    <value>no</value>
	    <value>yes</value>
	    <value>both</value>
	    </allowed>
    </param>

    <param type="bool" name="verbose">
	    <description>Output lots of information while the filler is working</description>
	    <value>False</value>
    </param>

    <param type="bool" name="overwrite">
	    <description>Over write an existing MS</description>
	    <value>False</value>
    </param>

    <param type="bool" name="showversion">
	    <description>Report the version of asdm2MS being used</description>
	    <value>False</value>
    </param>

    <constraints>
            <when param="singledish">
                <equals type="bool" value="False"/>
                <equals type="bool" value="True">
                    <default param="antenna"><value type="int">0</value></default>
                </equals>
            </when>
    </constraints>

    </input>

  <returns type="void"/>

  <example>
Convert an ALMA Science Data Model observation into a CASA visibility file (MS) or single-dish data format (Scantable).
The conversion of the ALMA SDM archive format into a measurement set.  This version
is under development and is geared to handling many spectral windows of different
shapes.
				          
Keyword arguments:
asdm -- Name of input ASDM file (directory)
        default: none; example: asdm='ExecBlock3'

vis       -- Root ms or scantable name, note a prefix (.ms or .asap) is NOT appended to this name
             default: none

singledish   -- Set True to write data as single-dish format (Scantable)
                default: False

            &gt;&gt;&gt; singledish expandable parameter
                 antenna -- antenna name or id.
 
corr_mode -- correlation mode to be considered on input. Could
	     be one or more of the following, ao, co, ac, or all
	     default: all

srt       -- spectral resolution type. Could be one or more of
	     the following, fr, ca, bw, or all
	     default: all

time_sampling -- specifies the time sampling, INTEGRATION and/or
                 SUBINTEGRAION. could be one or more of the following
                 i, si, or all.
		 default: all

ocorr_mode    -- output data for correlation mode AUTO_ONLY 
                 (ao) or CROSS_ONLY (co) or CROSS_AND_AUTO (ca)
		 default: ca
		 

compression  -- produces comrpressed columns in the resulting measurement set.
                default: False


asis         --  creates verbatim copies of the ASDM tables in 
                 the output measurement set. The value given to
		 this option must be a list of table names separated
		 by space characters; the wildcard character '*' is 
                 allowed in table names.

wvr_corrected_data -- specifies wich values are considered in the 
                      ASDM binary data to fill the DATA column in 
                      the MAIN table of the MS. Expected values for 
                      this option are 'no' for the uncorrected data 
                      (this is the default), 'yes' for the corrected
                      data and 'both' for corrected and uncorrected 
                      data. In the latter case, two measurement sets
                      are created, one containing the uncorrected 
                      data and the other one, whose name is suffixed
                      by '-wvr-corrected', containing the corrected 
                      data.


verbose     -- produce log output as asdm2MS is being run

showversion -- report the version of the asdm2MS being used.

  </example>

</task>

</casaxml>

=== sanbee/capps/trunk/CASACode/code/xmlcasa/tasks/imcontsub.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>

<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/xmlcasa/xml/casa.xsd">


<!-- This is the image continuum subtraction task                           -->
<!-- step 1: construct region with the region manger tool, rg               -->
<!-- step 2: do the subtraction, with ia.continuumsub (image analysis tool) -->
<!--                                                                        -->
<!-- TODO: Add polarization selection                                       -->
<!--       Add fitorder option value                                        -->
<!--       Verify that region selection with region manager works           -->
<!--       Expand region selection                                          -->

<task type="function" name="imcontsub" category="image analysis">
<shortdescription>Subtracts specified continuum channels from a spectral line data set</shortdescription>

<input>
    <param type="string" name="imagename" mustexist="true" >
    	<description>Name of the input spectral line image</description>
    	<value></value>
        <example>inputfile=ngc5921_task.image</example>
    </param>

    <param type="string" name="linefile" >
    	<description>Output line-cont image file name</description>
    	<value></value>
        <example>outline=ngc5921_line.image</example>
    </param>

    <param type="string" name="contfile" >
    	<description>Output continuum image file name</description>
    	<value></value>
        <example>outcont=ngc5921_cont.image</example>
    </param>


    <param type="int" name="fitorder" >
    	<description>Polynomial order for the continuum estimation</description>
    	<value>0</value>
	 
        <example>fitorder=2</example>
    </param>

    <param type="string" name="region">
        <description>Image region used for continuum area</description>
        <value></value>
    </param>

    <param type="string" name="box">
        <description>Box pixels regions for continuum area</description>
        <value></value>
    </param>

    <param type="string" name="chans" >
	<description>Channel ranges for continuum</description>
    	<value></value>
    </param>

    <param type="string" name="stokes">
	    <description>Stokes params to image (I,IV,IQU,IQUV)</description>
	    <value></value>
    </param>

    <constraints>
    </constraints>
</input>
<returns type="void"/>



<example>

        For a spectral line image, the regions to determine the continuum
        regions are first defined.  A graphical interface 'regions' is
        the most versatile method of selecting the line-free regions.  For
        a multi-spw image, the chanellization must be the same for all.

        The continuum channels are specified and two output images are made: a
        continuum image and a continuum-subtracted spectral line image.

	The continuum subtraction can be applied to either the whole image 
	(default) or a selected regions.  Regions are specified via 
	the box,chans, and stokes parameters or with a region file 
        given by the region parameter.

	Keyword arguments:
	imagename -- Input spectral line image
		Default: none; Example: imagename='ngc5921_task.im'
	linefile -- Name of output line image
		Default: none; Example: outline='ngc5921_line.im'
	contfile -- Name of output continuum image
		Default: none; Example: contfile='ngc5921_cont.im'
        fitorder -- Polynomial order for the continuum estimation.
                Default: 0; Example fitorder=2
        region -- ImageRegion file to define continuum
                Default: ''; none
                Example: region='myimage.im.rgn'
                         region='region1'
                Use the viewer on the image cube to define the continuum,
                   regions.  More general than box/chans.  Still experimental
                to retrieve the list of names.
	box --  A box region on the directional plane
	        ONLY pixel values acceptable at this time.
		Default: none (whole 2-D plane); Example: box='10,10,50,50'
	chans -- channel numbers go select for the continuum,
	        ONLY channel numbers accepted at this time.
		Default: none (all); 
                  Example: chans='3~6;>40'
	stokes -- Stokes parameters to image, may or may not be separated
                by commas but best if you use commas.
                Default: none (all); Example: stokes='IQUV';
                Options: 'I','Q','U','V','RR','RL','LR','LL','XX','YX','XY','YY', ... 


</example>


</task>

</casaxml>

=== sanbee/capps/CASACode/code/xmlcasa/tasks/hanningsmooth.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
      file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<task type="function" name="hanningsmooth" category="calibration">
	<shortdescription>Hanning smooth frequency channel data to remove Gibbs ringing</shortdescription>
	<description>This function Hanning smoothes the frequency channels with
        a weighted running average of smoothedData[i] =
        0.25*correctedData[i-1] + 0.50*correctedData[i] +
        0.25*correctedData[i+1].  The first and last channels are flagged.
        Inclusion of a flagged value in an average causes that data value
        to be flagged.
	WARNING: by default, all visibility columns will be smoothed. This will 
                 modify the DATA column of the output MS in order to make sure that
		 later gaincal will work on the smoothed data, e.g. as part of self-cal.
	</description>
	<input>
		<param type="string" name="vis">
			<description>Name of input visibility file (MS)</description>
			<value></value>
                        <example>vis='ngc5921.ms'</example>
		</param>
                <param type="string" name="datacolumn" ignorecase="True">
		  <description>the name of the MS column into which to write the smoothed data</description>
		  <value>all</value>
		  <allowed kind="enum">
		    <value>corrected</value>
		    <value>data</value>
		    <value>all</value>
		  </allowed>
		</param>
		<param type="string" name="outputvis">
			<description>name of the output visibility file (MS)</description>
			<value></value>
                        <example>outputvis='ngc5921-hs.ms'</example>
		</param>
	</input>
<returns type="void"/>

<example>

    This function Hanning smoothes the frequency channels with
    a weighted running average of smoothedData[i] =
    0.25*correctedData[i-1] + 0.50*correctedData[i] +
    0.25*correctedData[i+1].  The first and last channels are flagged.
    Inclusion of a flagged value in an average causes that data value
    to be flagged.
    WARNING: by default, all visibility columns will be smoothed. This will 
             modify the DATA column of the output MS in order to make sure that
             later gaincal will work on the smoothed data, e.g. as part of self-cal.

    Keyword arguments:
    vis -- Name of input visibility file (MS)
           default: none; example: vis='ngc5921.ms'
    datacolumn -- the name of the MS column into which to write the smoothed data
                  default='all'; example: datacolumn='corrected'
                  options: 'corrected', 'data', 'all'
    outputvis -- name of the output visibility file (MS)
                 default=none (write to the input MS); example: outputvis='ngc5921_src.ms'

    hanningsmooth(vis='ngc4852.ms', datacolumn='data', outputvis='ngc4852-hs.ms')		 


 </example>
 </task>
 </casaxml>

=== sanbee/capps/trunk/CASACode/code/xmlcasa/tasks/imstat.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>

<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/xmlcasa/xml/casa.xsd">


<!-- This is the image statitics task                         -->

<task type="function" name="imstat" category="image analysis, information">
<shortdescription>Displays statistical information from an image or image region</shortdescription>

<input>
    <param type="string" name="imagename" kind="image" mustexist="true" >
    	<description>Name of the input image</description>
    	<value></value>
        <example>imagenam=ngc5921_task.image</example>
    </param>

    <param type="string" name="region">
        <description>Image Region or name. Use Viewer</description>
        <value></value>
    </param>

    <param type="string" name="box">
        <description>Select one or more box regions</description>
        <value></value>
    </param>

    <param type="string" name="chans" >
	<description>Select the channel(spectral) range</description>
    	<value></value>
	<example>1.4126GHz~1.428GHz  # between 2 frequency</example>
	<example>1.4km/s             # above the given velocity</example>
        <example>!1~5                # Select all but the ange of channel numbers</example>
    </param>

    <param type="string" name="stokes">
	    <description>Stokes params to image (I,IV,IQU,IQUV)</description>
	    <value></value>
	    <example>stokes=&quot;IQ&quot;</example>
	    <example>stokes=&quot;RR,LL&quot;</example>
    </param>

    <param type="bool" name="list">
        <description>Print stats to logger?</description>
        <value>True</value>
    </param>

    <param type="bool" name="verbose">
        <description>Print additional messages to logger?</description>
        <value>True</value>
    </param>

    <constraints>
    </constraints>
</input>
    <output>
    <param type="any" name="xstat">
    	<description>Statistical values found for the image or region</description>
	<any type="variant"/>
	<value>{}</value>
    </param>
    </output>
<returns type="void"/>

<example>

     Many parameters are determined from the specified region of an image.
     For this version, the region can be specified by a set of rectangular
     pixel coordinates, the channel ranges and the Stokes.

     For directed output, run as 
                    myoutput = imstat()
   

	Keyword arguments:
	imagename -- Name of input image
		Default: none; Example: imagename='ngc5921_task.im'
        region -- File path to an ImageRegion file or name.
                Use the viewer, then region manager to select regions of
                   the image to process.  Similar to box, but graphical
                Or the name of a region stored with the image, 
                      use rg.namesintable()
                to retrieve the list of names.
                Default: none
                Example: region='myimage.im.rgn'
                         region='region1'
	box --  A box region on the directional plane
	        Only pixel values acceptable at this time.
		Default: none (whole 2-D plane); 
                  Example: box='10,10,50,50'
                      box = '10,10,30,30,35,35,50,50' (two boxes)
	chans -- channel numbers
	        Range of channel numbers to include in statistics
                  All spectral windows are included
		Default:''= all;  Example: chans='3~20'    
	stokes -- Stokes parameters to analyze.
                Default: none (all); Example: stokes='IQUV';  
                                     Example:stokes='I,Q'
                Options: 'I','Q','U','V','RR','RL','LR','LL','XX','YX','XY','YY', ...

      General procedure:

         1.  Specify inputs, then

         2.  myoutput = imstat()
               or specify inputs directly in calling sequence to task
             myoutput = imstat(imagename='image.im', etc)

         3.  myoutput['KEYS'] will contain the result associated with any
               of the keys given below
        
        KEYS CURRENTLY AVAILABLE
    	blc          - absolute PIXEL coordinate of the bottom left corner of 
	               the bounding box surrounding the selected region
    	blcf         - Same as blc, but uses WORLD coordinates instead of pixels
    	trc          - the absolute PIXEL coordinate of the top right corner 
                       of the bounding box surrounding the selected region
    	trcf         - Same as trc, but uses WORLD coordinates instead of pixels
        flux         - the integrated flux density if the beam is defined and 
                       the if brightness units are $Jy/beam$
	npts         - the number of unmasked points used
	max          - the maximum pixel value
    	min          - minimum pixel value
	maxpos       - absolute PIXEL coordinate of maximum pixel value
	maxposf      - Same as maxpos, but uses WORLD coordinates instead of pixels
    	minpos       - absolute pixel coordinate of minimum pixel value
	minposf      - Same as minpos, but uses WORLD coordinates instead of pixels
	sum          - the sum of the pixel values: $\sum I_i$
        sumsq        - the sum of the squares of the pixel values: $\sum I_i^2$
	mean         - the mean of pixel values: 
                       $\bar{I} = \sum I_i / n$
	sigma        - the standard deviation about the mean: 
                       $\sigma^2 = (\sum I_i - \bar{I})^2 / (n-1)$
        rms          - the root mean square: 
                       $\sqrt {\sum I_i^2 / n}$
	median       - the median pixel value (if robust=T)
	medabsdevmed - the median of the absolute deviations from the 
                       median (if robust=T)    
	quartile     - the inter-quartile range (if robust=T). Find the points 
                       which are 25% largest and 75% largest (the median is 
                       50% largest), find their difference and divide that 
                       difference by 2.

	Additional Examples
	# Selected two box region
	# box 1, bottom-left coord is 2,3 and top-right coord is 14,15
	# box 2, bottom-left coord is 30,31 and top-right coord is 42,43
	imstat( 'myImage', box='2,3,14,15;30,31,42,43' )

	# Select the same two box regions but only channels 4 and 5
	imstat( 'myImage', box='2,3,14,15;30,31,42,43', chan='4~5' )

	# Select all channels greater the 20 as well as channel 0.
 	# Then the mean and standard deviation are printed
	results = imstat( 'myImage', chans='&gt;20;0' )
        print "Mean is: ", results['mean'], "  s.d. ", results['sigma']

        # Find statistical information for the Q stokes value only
        # then the I stokes values only, and printing out the statistical
        # values that we are interested in.
	s1 = imstat( 'myimage', stokes='Q' )
	s2 = imstat( 'myimage', stokes='I' )
        print &quot;       |  MIN  |   MAX  | MEAN&quot;
        print &quot;  Q    | &quot;,s1['min'][0],&quot;  |  ",s1['max'][0],&quot;  |  ",,&quot;  |  ",s1['mean'][0]
        print &quot;  I    | &quot;,s2['min'][0],&quot;  |  ",s2['max'][0],&quot;  |  ",,&quot;  |  ",s2['mean'][0]

</example>

</task>

</casaxml>
